/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AbuseReportDetailsAllOf { 
    filename?: string;
    filesize?: number;
    shortUrl?: string;
    uploader_email?: string;
    uploader_name?: string;
    uploader_status?: string;
}

