/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileLog { 
    /**
     * ID of the file
     */
    fileId: string;
    /**
     * Download date of file
     */
    downloadDate: string;
    /**
     * recipient of the file
     */
    recipient: string;
    /**
     * download link
     */
    downloadLink: string;
}

