/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileLog } from './fileLog';
import { Recipient } from './recipient';


export interface FileInfoUploaderAllOf { 
    /**
     * file id
     */
    fileId: string;
    /**
     * User IDs this file is shared with
     */
    sharedWith: Array<Recipient>;
    /**
     * File logs
     */
    fileLogs: Array<FileLog>;
    status?: FileInfoUploaderAllOf.StatusEnum;
}
export namespace FileInfoUploaderAllOf {
    export type StatusEnum = 'AVAILABLE' | 'ALLOCATED' | 'DELETED';
    export const StatusEnum = {
        AVAILABLE: 'AVAILABLE' as StatusEnum,
        ALLOCATED: 'ALLOCATED' as StatusEnum,
        DELETED: 'DELETED' as StatusEnum
    };
}


