/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Recipient } from './recipient';


export interface FileRequestAllOf { 
    /**
     * Password protecting the file
     */
    password?: string;
    /**
     * Email notification sent after download if set to true
     */
    downloadNotification?: boolean;
    /**
     * User IDs this file is shared with
     */
    sharedWith: Array<Recipient>;
}

