/**
 * EasyShare
 * This is a API definition for the EasyShare service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipientWithLink } from './recipientWithLink';


export interface FileInfoUploaderAllOf { 
    /**
     * file id
     */
    fileId: string;
    /**
     * User IDs this file is shared with
     */
    sharedWith: Array<RecipientWithLink>;
}

