/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileStatusUpdate { 
    /**
     * New status of the file
     */
    status: FileStatusUpdate.StatusEnum;
}
export namespace FileStatusUpdate {
    export type StatusEnum = 'FROZEN' | 'AVAILABLE' | 'DELETED';
    export const StatusEnum = {
        Frozen: 'FROZEN' as StatusEnum,
        Available: 'AVAILABLE' as StatusEnum,
        Deleted: 'DELETED' as StatusEnum
    };
}


