/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LastUpload { 
    uploader_email?: string;
    share_email?: string;
    filename?: string;
    file_size?: number;
    path?: string;
    status?: string;
    created?: string;
    shorturl?: string;
    download_notification?: boolean;
}

