/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LastDownload { 
    uploader_email?: string;
    recipient?: string;
    filename?: string;
    path?: string;
    password?: string;
    shorturl?: string;
    download_notification?: boolean;
    download_date?: string;
}

