/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Recipient { 
    /**
     * Email of the recipient
     */
    email?: string;
    /**
     * Optional message to send
     */
    message?: string;
    /**
     * Download link to a specific file
     */
    downloadLink?: string;
    /**
     * Short link to a specific file
     */
    shortUrl?: string;
    /**
     * Email notification sent after download if set to true
     */
    downloadNotification?: boolean;
}

