/*
CIRCABC Share - a module of CIRCABC
Copyright (C) 2019 European Commission

This file is part of the "CIRCABC Share" project.

This code is publicly distributed under the terms of EUPL-V1.2 license,
available at root of the project or at https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12.
*/
/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfoAllOf { 
    /**
     * User ID
     */
    id: string;
    /**
     * Abbreviated user name used for login
     */
    loginUsername: string;
    /**
     * Full name of the user
     */
    givenName?: string;
    /**
     * Email address
     */
    email: string;
    /**
     * role
     */
    role?: UserInfoAllOf.RoleEnum;
    /**
     * True if the user is admin
     */
    isAdmin: boolean;
}
export namespace UserInfoAllOf {
    export type RoleEnum = 'ADMIN' | 'INTERNAL' | 'EXTERNAL' | 'TRUSTED_EXTERNAL' | 'API_KEY';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        INTERNAL: 'INTERNAL' as RoleEnum,
        EXTERNAL: 'EXTERNAL' as RoleEnum,
        TRUSTEDEXTERNAL: 'TRUSTED_EXTERNAL' as RoleEnum,
        APIKEY: 'API_KEY' as RoleEnum
    };
}


