/*
CIRCABC Share - a module of CIRCABC
Copyright (C) 2019 European Commission

This file is part of the "CIRCABC Share" project.

This code is publicly distributed under the terms of EUPL-V1.2 license,
available at root of the project or at https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12.
*/
/**
 * CIRCABC Share
 * This is a API definition for the CIRCABC Share service.
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfo { 
    /**
     * Total space the user has (Bytes)
     */
    totalSpace: number;
    /**
     * Space the user already used (Bytes)
     */
    usedSpace: number;
    /**
     * Number of files
     */
    filesCount?: number;
    /**
     * User ID
     */
    id: string;
    /**
     * Abbreviated user name used for login
     */
    loginUsername: string;
    /**
     * Full name of the user
     */
    givenName?: string;
    /**
     * Email address
     */
    email: string;
    /**
     * role
     */
    role?: UserInfo.RoleEnum;
    /**
     * True if the user is admin
     */
    isAdmin: boolean;
    /**
     * status = REGULAR (keep all user\'s rights) - Users who have full access to the site; SUSPENDED (Prevent users from uploading) - Users who can log in and download, but cannot upload; BANNED (prevent user from login) - Users who cannot log in at all.
     */
    status?: UserInfo.StatusEnum;
}
export namespace UserInfo {
    export type RoleEnum = 'ADMIN' | 'INTERNAL' | 'EXTERNAL' | 'TRUSTED_EXTERNAL' | 'API_KEY';
    export const RoleEnum = {
        Admin: 'ADMIN' as RoleEnum,
        Internal: 'INTERNAL' as RoleEnum,
        External: 'EXTERNAL' as RoleEnum,
        TrustedExternal: 'TRUSTED_EXTERNAL' as RoleEnum,
        ApiKey: 'API_KEY' as RoleEnum
    };
    export type StatusEnum = 'REGULAR' | 'SUSPENDED' | 'BANNED';
    export const StatusEnum = {
        Regular: 'REGULAR' as StatusEnum,
        Suspended: 'SUSPENDED' as StatusEnum,
        Banned: 'BANNED' as StatusEnum
    };
}


