// Build information, automatically generated by `ng-info`
const build = {
  version: '1.0.0',
  timestamp: 'Tue Jan 01 2022 00:00:00 GMT+0000 (Coordinated Universal Time)',
  message: null,
  git: {
    user: null,
    branch: null,
    hash: 'e3f9b4',
    fullHash: 'e3f9b4e562623c8a69a85d8516afe368c85348f7',
  },
};

export default build;
