// Build information, automatically generated by `ng-info`
const build = {
    version: "1.0.1",
    timestamp: "Tue Aug 23 2022 21:00:18 GMT+0000 (Coordinated Universal Time)",
    message: null,
    git: {
        user: null,
        branch: null,
        fullHash: null
    }
};

export default build;