// Build information, automatically generated by `ng-info`
const build = {
    version: "1.0.0",
    timestamp: "Tue Jan 01 2022 00:00:00 GMT+0000 (Coordinated Universal Time)",
    message: null,
    git: {
        user: null,
        branch: null,
        fullHash: "1234567"
    }
};

export default build;