server:
  port: 8080
cors:
  origin: '*'

spring:
  profiles:
    active: @spring.profiles.active@
 
  servlet:
    multipart:
      enabled: false
      max-file-size: 5GB
      max-request-size: 5GB
      
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
eushare:
  expirationdays: 7
  defaultuserspace: 5368709120
  # 4Gb
  maxSizeAllowedInBytes: 4294967296 
  activateMailService: true
