server:
  port: 8080
cors:
  origin: '*'
eushare:
  clientHttpAddress: http://localhost
  expirationdays: 7
  defaultuserspace: 5368709120
  # 4Gb
  maxSizeAllowedInBytes: 4294967296 
  activateMailService: true
  disks:
    - /eushare/
logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: ERROR
spring:
  profiles:
    active: @spring.profiles.active@
 
  servlet:
    multipart:
      enabled: false
      max-file-size: 256MB
      max-request-size: 256MB
      
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs