cors:
  origin: '*'
easyshare:
  expirationdays: 7
  defaultuserspace: 5368709120
  # 4Gb
  maxSizeAllowedInBytes: 4294967296 
  activateMailService: false
  disks:
    - /easyshare/
logging:
  level:
    org.springframework: ERROR
    org.hibernate.SQL: DEBUG
spring:
  jackson:
    date-format: com.circabc.easyshare.RFC3339DateFormat
    serialization: 
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    #jdbc:oracle:thin:@localhost:1521:testing
    url: jdbc:mysql://db/easyshare
    username: easyshare
    password: easyshare
    driver:
      #oracle.jdbc.driver.OracleDriver
      class: com.mysql.jdbc.Driver
  jpa:
    #org.hibernate.dialect.Oracle10gDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  mail:
    host: localhost
    port: 25
    username: username
    password: password
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs