
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://ecas-mockup.cc.cec.eu.int:7002/cas/oauth2/token/introspect
          client-id: VtwvhHcuGQFNUV519SdUj7ZXFztOqUqKyizqyusEHYyeq4zWWg0wlrsCH2C2k2UOdRP7BSzgl5ZCxpC8YsaRQRy-l0EvyMANoKy8j6knSKYyfa
          client_secret: WMq48iaCiYMh2qWTbibco_zQ9afXy4peIlk4NlM9htGrKYPhAQ1mR5JesbWVaxacAkiUagbXDTwMWCN3YP8vJbYRXWMFV1nZkGTj3fiDKSY95Dkw__aTAIcaUcyAn_hobZE6nnMvSO84AO1706yK5YnvObzCsTO6DFyeCtApAlM
  datasource:
    #jdbc:oracle:thin:@localhost:1521:testing
    url: jdbc:mysql://db/easyshare
    username: easyshare
    password: easyshare
    driverClassName: com.mysql.cj.jdbc.Driver 
    continue-on-error: true

  jpa:
    #org.hibernate.dialect.Oracle10gDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: maildev
    port: 25
    username: username
    password: password