spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://ecas-mockup:7002/cas/oauth2/token/introspect
          client-id: my_client_id
          client_secret: my_client_secret
  datasource:
    #continue-on-error: true
    #jdbc:oracle:thin:@localhost:1521:testing
    url: jdbc:mysql://db/easyshare
    username: easyshare_username
    password: easyshare_password
    driverClassName: com.mysql.cj.jdbc.Driver 
  jpa:
    #org.hibernate.dialect.Oracle10gDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: maildev
    port: 25
    username: username
    password: password