server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1  
cors:
  origin: '*'

spring:
  profiles:
    active: @spring.profiles.active@
 
  servlet:
    multipart:
      enabled: false
      max-file-size: -1
      max-request-size: -1
      
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
eushare:
  expirationdays: 7
  defaultuserspace: 5368709120
  # 4Gb
  maxSizeAllowedInBytes: 4294967296 
  activateMailService: true
