server:
  port: 8888
spring:
  profiles: dev
  security:
    adminusers: bournja
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://localhost:7002/cas/oauth2/token/introspect
          client-id: DXTGxI4DLJqwjOLTfNxIdjpIjL1XQkWblqLmHqfkFivnonNmzkaZkRmzpg2dZUZPEX5n5EBULOTBLMwGy2JyLt-PnCd3ypAN98BmSAcZ2paw8
          client-secret: uXI7LSvJEadw_0PoxmjcelbWrvKVPppgufkui30ewtu9qCIv3DGNpvqhctwXizmWSIfPybG9LM1PGC4IXXDPiK22yWnhjMNpoH2yVSzIPcR31GF4e7XM72xHlTrmb74vcp6Y8meI_PMxENBZ5V2nMtW4qqmfNp8rp1lIULDDqm4
  datasource:
    #jdbc:oracle:thin:@localhost:1521:testing
    url: jdbc:mysql://localhost:3306/easyshare
    username: easyshare
    password: easyshare
    driver:
      #oracle.jdbc.driver.OracleDriver
      class: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #org.hibernate.dialect.Oracle10gDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
eushare:
  expirationdays: 7
  defaultuserspace: 5368709120
  # 4Gb
  maxSizeAllowedInBytes: 4294967296 
  activateMailService: true
  disks:
    - /eushare/
  clientHttpAddress: http://localhost:8080