version: "3.7"
services:
  db:
    container_name: eushare_db
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=password
    volumes:
        - ./mysql:/docker-entrypoint-initdb.d/:ro
    command: --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED
  server:
    build: server-tomcat
   # image: eushare-dev-tomcat-server
    extra_hosts:
      eulogin: 172.19.0.1
    volumes:
      - type: bind
        source: ~/eushare-data
        target: /easyshare/
    container_name: eushare_dev_server
    depends_on:
      - db
  client:
    build: client-tomcat
  # image: eushare-dev-tomcat-client
    container_name: eushare_dev_tomcat_client
    ports:
      - "8888:8080"
    depends_on:
      - server
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
  proxy:
    image: nginx:alpine
    container_name: nginx_eushare_proxy
    volumes:
      - ./proxy/conf/nginx-tomcat.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
     # - 443:443 incompatible with AWS workspace pcoip-agent
    depends_on:
      - client
