/**
 * EasyShare
 * This is a API definition for the EasyShare service.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Recipient { 
    /**
     * User ID (email in case of external user)
     */
    emailOrID: string;
    /**
     * Optional message to send
     */
    message?: string;
}

