/**
 * EasyShare
 * This is a API definition for the EasyShare service.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Recipient } from './recipient';


export interface RecipientWithLink { 
    /**
     * Email or name of the recipient
     */
    emailOrName: string;
    /**
     * Optional message to send
     */
    message?: string;
    /**
     * True to send an email with the download link
     */
    sendEmail?: boolean;
    /**
     * Id of the recipient
     */
    recipientId?: string;
    /**
     * Download link to a specific file
     */
    downloadLink: string;
}

