/**
 * EasyShare
 * This is a API definition for the EasyShare service.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSpace } from './userSpace';


export interface UserInfo { 
    /**
     * Total space the user has (Bytes)
     */
    totalSpace: number;
    /**
     * Space the user already used (Bytes)
     */
    usedSpace: number;
    /**
     * User ID (email address in case of external user)
     */
    id: string;
    /**
     * Files the user has uploaded
     */
    uploadedFiles: Array<string>;
    /**
     * Files the user has given access to
     */
    sharedFiles: Array<string>;
    /**
     * True if the user is admin
     */
    isAdmin: boolean;
}

