version: "3.7"
services:
  db:
    container_name: db
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=password
    volumes:
        - ./mysql:/docker-entrypoint-initdb.d/:ro
    command: --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED
  server:
    build: server
    image: tomcat-easyshare-server
    extra_hosts:
      ecas-mockup.cc.cec.eu.int: 10.69.125.187
    volumes:
      - type: bind
        source: ~/eushare-data
        target: /easyshare/
      - type: bind
        source: ../server/src
        target: /app/src
      - type: bind
        source: ../server/target
        target: /app/target
    ports:
      - "8888:8080"
      - "8886:8886"
    environment:
      - JPDA_ADDRESS:8886
      - JPDA_TRANSPORT:dt_socket
    container_name: tomcat_easyshare_server
    depends_on:
      - db
  client:
    build: client
    image: tomcat-easyshare-client
    ports:
      - "8080:4200"
    container_name: tomcat_easyshare_client
    depends_on:
      - server
    volumes:
      - type: bind
        source: ../client/angular/
        target: /app
      - /app/node_modules/
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
  proxy:
    image: nginx:alpine
    container_name: nginx_easyshare_proxy
    volumes:
      - ./proxy/conf/noSSL_nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
     # - 443:443 incompatible with AWS workspace pcoip-agent
    depends_on:
      - client
